version = 0.1

[1]
[1.global]
[1.global.parameters]
stack_name = "api-gateway-examples-dev"
s3_prefix = "api-gateway-examples-dev"
s3_bucket = "aws-sam-cli-managed-dev-api-gatew-artifactsbucket-122f2zrpvih3o"
region = "us-east-1"

[1.deploy]
[1.deploy.parameters]
template = "packaged-testing.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""

# ############################################## #

[2]
[2.global]
[2.global.parameters]
stack_name = "api-gateway-examples-prod"
s3_prefix = "api-gateway-examples-prod"
s3_bucket = "aws-sam-cli-managed-prod-api-gate-artifactsbucket-1dphx6uzqr7cp"
region = "us-east-1"

[2.deploy]
[2.deploy.parameters]
template = "packaged-prod.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""

# ############################################## #

[pipeline]
[pipeline.deploy]
[pipeline.deploy.parameters]
stack_name = "api-gateway-examples"
s3_prefix = "api-gateway-examples"
resolve_s3 = true
fail_on_empty_changeset = false
template = "codepipeline.yaml"
capabilities = "CAPABILITY_IAM"
