version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dev-capstone"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sz6nx9l8kven"
s3_prefix = "dev-capstone"
region = "us-east-1"
profile = "geekcafe-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
